# Generated by Django 6.0.4 on 2026-05-05 22:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('series_type', models.CharField(choices=[('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua')], max_length=10)),
                ('author', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('total_chapters', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_series', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='tracker.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('pause', 'En pause'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_series', to='tracker.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_entries', to='tracker.userseries')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userseries',
            index=models.Index(fields=['user', 'status'], name='tracker_use_user_id_5f280d_idx'),
        ),
        migrations.AddIndex(
            model_name='userseries',
            index=models.Index(fields=['user', 'is_favorite'], name='tracker_use_user_id_6a46f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userseries',
            unique_together={('user', 'series')},
        ),
        migrations.AddIndex(
            model_name='readingentry',
            index=models.Index(fields=['user_series', '-chapter_number'], name='tracker_rea_user_se_a95d3b_idx'),
        ),
    ]
