# Generated by Django 4.2.30 on 2026-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='total_chapters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
