# Generated by Django 6.0.4 on 2026-05-08 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_series_total_chapters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site de lecture',
                'verbose_name_plural': 'Sites de lecture',
                'ordering': ['name'],
            },
        ),
    ]
